################
# DrupalCI GitLabCI template
#
# Gitlab-ci.yml to replicate DrupalCI testing for Contrib
#
# With thanks to:
#   * The GitLab Acceleration Initiative participants
#   * DrupalSpoons
################

################
# Guidelines
#
# This template is designed to give any Contrib maintainer everything they need to test, without requiring modification. It is also designed to keep up to date with Core Development automatically through the use of include files that can be centrally maintained.
#
# However, you can modify this template if you have additional needs for your project.
################

################
# Includes
#
# Additional configuration can be provided through includes.
# One advantage of include files is that if they are updated upstream, the changes affect all pipelines using that include.
#
# Includes can be overridden by re-declaring anything provided in an include, here in gitlab-ci.yml
# https://docs.gitlab.com/ee/ci/yaml/includes.html#override-included-configuration-values
################

include:
  ################
  # DrupalCI includes:
  # As long as you include this, any future includes added by the Drupal Association will be accessible to your pipelines automatically.
  # View these include files at https://git.drupalcode.org/project/gitlab_templates/
  ################
  - project: $_GITLAB_TEMPLATES_REPO
    # "ref" value can be:
    # - Recommended (default) - `ref: $_GITLAB_TEMPLATES_REF` - The Drupal Association will update this value to the recommended tag for contrib.
    # - Latest - `ref: main` - Get the latest additions and bug fixes as they are merged into the templates.
    # - Minor or Major latests - `ref: 1.x-latest` or `ref: 1.0.x-latest` - Get the latest additions within a minor (mostly bugfixes) or major (bugs and new features).
    # - Fixed tag - `ref: 1.0.1` - Set the value to a known tag. This will not get any updates.
    # If you change the default value of ref, you should set the _CURL_TEMPLATES_REF variable in the variables section to be the same as set here.
    ref: 1.12.x-latest
    file:
      - "/includes/include.drupalci.main.yml"
      # For Drupal 7, remove the above line and uncomment the below.
      # - "/includes/include.drupalci.main-d7.yml"
      - "/includes/include.drupalci.variables.yml"
      - "/includes/include.drupalci.workflows.yml"
  # Local includes
  - local: .gitlab/ci/drupal.yml
  - local: .gitlab/ci/test.yml

stages:
  - development
  - build
  - validate
  - test
  - publish

#
################
# Pipeline configuration variables
#
# These are the variables provided to the Run Pipeline form that a user may want to override.
#
# Docs at https://git.drupalcode.org/project/gitlab_templates/-/blob/main/includes/include.drupalci.variables.yml
################
variables:
  # This needs to match $_GITLAB_TEMPLATES_REPO `ref`. Omit if `ref` value is `_GITLAB_TEMPLATES_REF`.
  _CURL_TEMPLATES_REF: 1.12.x-latest
  # Show env variables always to help with debugging.
  _SHOW_ENVIRONMENT_VARIABLES: 1

  # Ignore that `ext-sodium` is not available in the CI environment.
  # It's required by a dependency of `drupal/simple_oauth`, but it doesn't cause any issues with what
  # `drupal/simple_oauth` does.
  # See https://git.drupalcode.org/project/simple_oauth/-/blob/6.0.x/.gitlab-ci.yml
  COMPOSER_IGNORE_PLATFORM_REQS: ext-sodium
  # Needed to allow this to run locally.
  # https://project.pages.drupalcode.org/gitlab_templates/info/test-locally/
  DRUPALORG_CI_SERVER_URL: https://git.drupalcode.org
  # Set this as CI_PROJECT_NAME changes on forks.
  CI_PARENT_PROJECT_NAME: canvas
  PHPUNIT_FAIL_ON_PHPUNIT_DEPRECATION: 0
  _CONCURRENCY_THREADS: '12'

  # Enable testing against next minor version of Drupal core
  OPT_IN_TEST_NEXT_MINOR: '1'
  # Target a specific 11.3 release, not 11.3.x-dev, to avoid breaking on evolving test expectations unnecessarily.
  CORE_NEXT_MINOR: 11.3.3

  # Enable Canvas contributors to change this from `true` to `false` to disable E2E (end-to-end) tests.
  # (Useful when early in an MR and/or developing low-level functionality that is unlikely to affect E2E tests.)
  _CANVAS_E2E_TESTS: true

# @todo Remove when https://www.drupal.org/project/gitlab_templates/issues/3452183 lands.
.is-push-rule: &is-push-rule
  if: $CI_PIPELINE_SOURCE == "push" && $CI_PROJECT_ROOT_NAMESPACE == "project"

.manual-rule: &manual-rule
  - when: manual
    allow_failure: true

# @todo Remove when https://www.drupal.org/project/gitlab_templates/issues/3452183 lands.
.php-files-change-rule: &php-files-change-rule
  - if: $_FOR_EVERY_MR_COMMIT == "true" || $_FOR_EVERY_MR_COMMIT == null
    changes:
      - "**/*.{php,module,inc,install,theme,profile}"
    when: on_success

# @todo Remove when https://www.drupal.org/project/gitlab_templates/issues/3452183 lands.
.css-files-change-rule: &css-files-change-rule
  - if: $_FOR_EVERY_MR_COMMIT == "true" || $_FOR_EVERY_MR_COMMIT == null
    changes:
      - "**/*.css"
      - package.json
      - ui/package.json
      - .prettierrc.json
    when: on_success

# @todo Remove when https://www.drupal.org/project/gitlab_templates/issues/3452183 lands.
.module-metadata-files-change-rule: &module-metadata-files-change-rule
  - if: $_FOR_EVERY_MR_COMMIT == "true" || $_FOR_EVERY_MR_COMMIT == null
    changes:
      - "**/*.yml"
    when: on_success

# @todo Remove when https://www.drupal.org/project/gitlab_templates/issues/3452183 lands.
.module-config-files-change-rule: &module-config-files-change-rule
  - if: $_FOR_EVERY_MR_COMMIT == "true" || $_FOR_EVERY_MR_COMMIT == null
    changes:
      # config schema and/or default config
      - config
    when: on_success

# @todo Remove when https://www.drupal.org/project/gitlab_templates/issues/3452183 lands.
.SDC-files-change-rule: &SDC-files-change-rule
  - if: $_FOR_EVERY_MR_COMMIT == "true" || $_FOR_EVERY_MR_COMMIT == null
    changes:
      - components
      - schema.json
      - "**/*.twig"
    when: on_success

.ui-fixture-files-change-rule: &UI-fixtures-files-change-rule
  - if: $_FOR_EVERY_MR_COMMIT == "true" || $_FOR_EVERY_MR_COMMIT == null
    changes:
      - ui/tests/fixtures/**/*
    when: on_success

.e2e-tests-are-enabled-rule: &e2e-tests-are-enabled-rule
  - if: $_CANVAS_E2E_TESTS == "true"

# Disable jobs from the upstream template.
phpcs:
  rules:
    - when: never

phpstan:
  rules:
    - when: never

cspell:
  rules:
    - when: never

composer-lint:
  rules:
    - when: never

phpstan (next minor):
  rules:
    - when: never

phpunit (next minor):
  rules:
    - when: never

phpcs-rules-match-drupal-11:
  stage: development
  script:
    - |
      # Download the file from the Drupal repository
      curl -o drupal_core_phpcs.xml.dist https://git.drupalcode.org/project/drupal/-/raw/11.x/core/phpcs.xml.dist?ref_type=heads

      # Check if the download was successful
      if [ $? -ne 0 ]; then
        echo "🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥"
        echo "Error: Failed to download $DRUPAL_URL"
        exit 1
      fi

      # Compare the downloaded file with the local file using a subshell to prevent premature exit
      echo "Comparing downloaded file with local file..."
      # With uses the braces the job just ends here for some reason.
       {
        diff drupal_core_phpcs.xml.dist core.phpcs.xml.dist
        DIFF_EXIT_CODE=$?
      } || true

      if [ $DIFF_EXIT_CODE -ne 0 ]; then
        echo "🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥"
        echo "Error: core.phpcs.xml.dist not up to date with Drupal 11.x core/phpcs.xml.dist. Please create an issue to update this file."
        echo "Issue template: https://www.drupal.org/node/add/project-issue/canvas?title=Update%20PHPCS%20config%20to%20match%20Drupal%2011&field_issue_parent=3512890&clone_body=1&categories=2&priorities=100&status=1&version=1.x-dev&component=Code&assigned=0&tags="
      else
        echo "👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍"
        echo "core.phpcs.xml.dist is up to date with Drupal 11.x core/phpcs.xml.dist"
      fi

      # Exit with the exit code of the diff command
      exit $DIFF_EXIT_CODE
  # Allow this to fail, to avoid disrupting Canvas's CI when upstream changes.
  allow_failure: true

stylelint:
  allow_failure: false
  # @todo Remove when https://www.drupal.org/project/gitlab_templates/issues/3452183 lands.
  rules:
    - *is-push-rule
    - *css-files-change-rule
    - *manual-rule
  before_script:
    # This job runs Prettier checks using what's installed in Drupal core.
    # Delete our custom .prettierrc.json, and use the one from Drupal core instead. This avoids problems with Prettier
    # plugins that are not installed in Drupal core, e.g., @ianvs/prettier-plugin-sort-imports.
    - rm -rf .prettierrc.json

# Tests the minimum Drupal core version Canvas supports: 11.2.
phpunit:
  # Auto-retry when random failures occur due to upstream bugs.
  # @see https://www.drupal.org/project/canvas/issues/3571997#comment-16458359
  retry:
    max: 2
    exit_codes: 112
  variables:
    # Note: Canvas uses `@group #slow` to start slow tests early. The threshold is (at the time of writing) ~60 seconds.
    _PHPUNIT_CONCURRENT: 1
    # 💡To run a single PHPUnit test, e.g. PropSourceTest, comment the above and uncomment the below.
    # _PHPUNIT_CONCURRENT: 0
    # _PHPUNIT_EXTRA: '--filter PropSourceTest'
  # TRICKY: duplicate all of the upstream `.phpunit-base`'s `script` to add conditional auto-retry functionality
  # @todo Work with upstream `gitlab_templates` project to allow this logic to be injected without repeating everything
  script:
    - cd $CI_PROJECT_DIR && pwd
    - !reference [ .check-composer-end-code ]
    - !reference [ .phpunit-webdriver-variables ]
    - !reference [ .show-environment-variables ]
    - !reference [ .setup-webserver ]
    - !reference [ .simpletest-db ]
    - !reference [ .show-context ]
    # Recipe projects require the test files to be real, not symlinks.
    - |
      if [[ $PROJECT_TYPE == "recipe" && _COMPOSER_SYMLINK != "0" ]]; then
        echo "Replacing the test file symlinks with real copied files"
        rm -Rvf $DRUPAL_PROJECT_FOLDER/tests
        cp -Rvp $CI_PROJECT_DIR/tests $DRUPAL_PROJECT_FOLDER
      fi
    # Remove all spaces from _PHPUNIT_TESTGROUPS for reliable checking and to
    # ensure only one string is passed to bin/phpunit or run-tests.sh
    - _PHPUNIT_TESTGROUPS=$(echo $_PHPUNIT_TESTGROUPS | sed -e 's/ //g')
    # Execute tests.
    - |
      if [ "$_PHPUNIT_CONCURRENT" == "0" ]; then
        echo "Webdriver arguments: '$MINK_DRIVER_ARGS_WEBDRIVER'"
        # if _PHPUNIT_TESTGROUPS is blank then do not add anything because the test group will be handled by the matrix.
        # if _PHPUNIT_TESTGROUPS is --all then do not add anything because the default is to run all tests in the module.
        # Otherwise add --group $_PHPUNIT_TESTGROUPS
        WHAT_TO_RUN=$([[ "$_PHPUNIT_TESTGROUPS" == "" || "$_PHPUNIT_TESTGROUPS" == "--all" ]] && echo "" || echo "--group $_PHPUNIT_TESTGROUPS")
        PHPUNIT_OPTIONS=''
        # If the project does not have its own phpunit.xml(.dist) then use the one from core. Only do this if no configuration options are specified in _PHPUNIT_EXTRA.
        if [[ ! -f "$CI_PROJECT_DIR/phpunit.xml" && ! -f "$CI_PROJECT_DIR/phpunit.xml.dist" && ! $_PHPUNIT_EXTRA =~ (-c |--configuration|--no-configuration) ]]; then
          echo "This project has no phpunit.xml(.dist), getting default from $_WEB_ROOT/core"
          cp -v $_WEB_ROOT/core/phpunit.xml.dist phpunit.xml
          source $CI_PROJECT_DIR/get-file-via-curl.sh scripts/prepare-phpunit-xml.php
          php prepare-phpunit-xml.php $VERBOSE_FLAG
          rm prepare-phpunit-xml.php
          printf "$DIVIDER\n"
        fi
        printf "_PHPUNIT_CONCURRENT=$_PHPUNIT_CONCURRENT, _PHPUNIT_TESTGROUPS=$_PHPUNIT_TESTGROUPS, _PHPUNIT_EXTRA=$_PHPUNIT_EXTRA\nPHPUNIT_OPTIONS=$PHPUNIT_OPTIONS, WHAT_TO_RUN=$WHAT_TO_RUN\n"
        # Create an empty phpunit-ignore.xml file because the phpunit binary does not write any phpunit-*.xml but the artifact definition needs one to exist.
        echo '<not-used/>' > $CI_PROJECT_DIR/$_WEB_ROOT/sites/default/files/simpletest/phpunit-ignore.xml
        echo "executing: sudo -u www-data -H -E $COMPOSER_BIN_DIR/phpunit $PHPUNIT_OPTIONS --bootstrap $PWD/$_WEB_ROOT/core/tests/bootstrap.php $DRUPAL_PROJECT_FOLDER --log-junit $CI_PROJECT_DIR/junit.xml $WHAT_TO_RUN $_PHPUNIT_EXTRA"
        sudo -u www-data -H -E $COMPOSER_BIN_DIR/phpunit $PHPUNIT_OPTIONS --bootstrap $PWD/$_WEB_ROOT/core/tests/bootstrap.php $DRUPAL_PROJECT_FOLDER --log-junit $CI_PROJECT_DIR/junit.xml $WHAT_TO_RUN $_PHPUNIT_EXTRA || EXIT_CODE=$?
      elif [ "$_PHPUNIT_CONCURRENT" == "1" ]; then
        # if _PHPUNIT_TESTGROUPS is blank then do not add anything, because the test group will be handled by the matrix.
        # if _PHPUNIT_TESTGROUPS is --all then add --directory $DRUPAL_PROJECT_FOLDER
        # Otherwise add $_PHPUNIT_TESTGROUPS (without the --group)
        WHAT_TO_RUN=$([[ "$_PHPUNIT_TESTGROUPS" == "" ]] && echo "" || ([[ "$_PHPUNIT_TESTGROUPS" == "--all" ]] && echo "--directory $DRUPAL_PROJECT_FOLDER" || echo "$_PHPUNIT_TESTGROUPS"))
        echo "_PHPUNIT_CONCURRENT=$_PHPUNIT_CONCURRENT, _PHPUNIT_TESTGROUPS=$_PHPUNIT_TESTGROUPS, _PHPUNIT_EXTRA=$_PHPUNIT_EXTRA, WHAT_TO_RUN=$WHAT_TO_RUN"
        # Create an empty junit.xml because run-tests.sh does not write to this file but the artifact needs to exist.
        echo '<not-used/>' > junit.xml
        echo "executing: sudo -u www-data -H -E php $_WEB_ROOT/core/scripts/run-tests.sh --php '$(which php)' --color --keep-results --concurrency $_CONCURRENCY_THREADS --repeat '1' --sqlite 'sites/default/files/.sqlite' --dburl $SIMPLETEST_DB --url $SIMPLETEST_BASE_URL --xml $CI_PROJECT_DIR/$_WEB_ROOT/sites/default/files/simpletest --verbose --non-html $WHAT_TO_RUN $_PHPUNIT_EXTRA"
        $COMPOSER_BIN_DIR/phpunit --version
        sudo -u www-data -H -E php $_WEB_ROOT/core/scripts/run-tests.sh --php "$(which php)" --color --keep-results --concurrency $_CONCURRENCY_THREADS --repeat "1" --sqlite "sites/default/files/.sqlite" --dburl $SIMPLETEST_DB --url $SIMPLETEST_BASE_URL --xml $CI_PROJECT_DIR/$_WEB_ROOT/sites/default/files/simpletest --verbose --non-html $WHAT_TO_RUN $_PHPUNIT_EXTRA || EXIT_CODE=$?
      fi
    - cp /var/log/apache2/test.apache.access.log $CI_PROJECT_DIR/apache.access.log.txt
    - cp /var/log/apache2/test.apache.error.log $CI_PROJECT_DIR/apache.error.log.txt
    # Auto-retry when random failures occur due to upstream bugs.
    # @see https://www.drupal.org/project/canvas/issues/3571997#comment-16458359
    # @todo Rewrite this after https://www.drupal.org/project/gitlab_templates/issues/3572371 lands
    - grep "RecursiveDirectoryIterator" $CI_PROJECT_DIR/$_WEB_ROOT/sites/default/files/simpletest/phpunit-*.xml && exit 112 || true
    - exit $EXIT_CODE
  needs:
    - composer
    - UI
  parallel:
    # @see https://www.drupal.org/node/3444548
    matrix:
      - _TARGET_DB_TYPE: sqlite
        _TARGET_DB_VERSION: '3'
        # @see https://git.drupalcode.org/project/drupal/-/commit/10466dba9d7322ed55165dd9224edb2153c9b27a
        _TARGET_PHP: '8.3-ubuntu'
        _FOR_EVERY_MR_COMMIT: 'true'
      - _TARGET_DB_TYPE: 'mariadb'
        _TARGET_DB_VERSION: '10.6'
        _FOR_EVERY_MR_COMMIT: 'false'
      - _TARGET_DB_TYPE: 'mysql'
        # @todo Delete this when https://www.drupal.org/project/gitlab_templates/issues/3447105 lands.
        _TARGET_DB_VERSION: '8'
        _FOR_EVERY_MR_COMMIT: 'false'
      - _TARGET_DB_TYPE: 'pgsql'
        _TARGET_DB_VERSION: '16'
        _FOR_EVERY_MR_COMMIT: 'false'
  # @todo Delete this after https://www.drupal.org/project/gitlab_templates/issues/3447792 lands.
  # @see https://git.drupalcode.org/issue/gitlab_templates-3447792/-/compare/main...3447792-raise-sqlite-version?from_project_id=96292, when 984abb7b4781559a13078d58bb65f6959fe42179 was the last commit.
  image:
    name: $_CONFIG_DOCKERHUB_ROOT/php-$PHP_VERSION-ubuntu-apache:$_TARGET_PHP_IMAGE_TAG
  # @todo Remove when https://www.drupal.org/project/gitlab_templates/issues/3452183 lands.
  rules:
    - *is-push-rule
    - *php-files-change-rule
    - *module-metadata-files-change-rule
    - *module-config-files-change-rule
    - *SDC-files-change-rule
    - *UI-fixtures-files-change-rule
    - *manual-rule

phpunit (11.3):
  extends: phpunit
  needs:
    - composer (next minor)
    - UI

prettier:
  stage: validate
  image: node:20-alpine
  allow_failure: false
  needs: []
  # @todo Refine when https://www.drupal.org/project/gitlab_templates/issues/3452183 lands.
  rules:
    - *is-push-rule
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - "**/*.js"
        - "**/*.jsx"
        - "**/*.ts"
        - "**/*.tsx"
        - "**/*.json"
        - "**/*.yml"
    - *manual-rule
  script:
    - npm ci
    - npm run lint:prettier

UI:
  stage: build
  image: node:20-alpine
  needs: []
  script:
    - npm ci
    # Verify building the entire app succeeds — this first runs the TypeScript Compiler.
    - npm run build --workspace=@drupal-canvas/ui
    # @todo In the future, when `ui/dist` and `packages/astro-hydration/dist` are
    # committed, verify here that they match.
  artifacts:
    paths:
      - ui/dist
      - packages/astro-hydration/dist

eslint:
  stage: validate
  image: node:20-alpine
  allow_failure: false
  needs: []
  # @todo Refine when https://www.drupal.org/project/gitlab_templates/issues/3452183 lands.
  rules:
    - *is-push-rule
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - "**/*.js"
        - "**/*.jsx"
        - "**/*.ts"
        - "**/*.tsx"
        - "**/*.json"
    - *manual-rule
  script:
    - npm ci
    - npm run lint:eslint -- --format=junit --output-file=$CI_PROJECT_DIR/ui-eslint-junit.xml --max-warnings=0
  artifacts:
    expose_as: junit
    expire_in: 6 mos
    when: always
    name: artifacts-$CI_PIPELINE_ID-$CI_JOB_NAME_SLUG
    paths:
      - ui-eslint-junit.xml
    reports:
      junit: ui-eslint-junit.xml

vitest:
  stage: test
  image: node:20-alpine
  allow_failure: false
  needs: []
  rules:
    - *is-push-rule
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - ui/src/**/*
        - ui/tsconfig.json
        - ui/tsconfig.node.json
        - ui/tests/vitest/**/*
    - *UI-fixtures-files-change-rule
    - *manual-rule
  script:
    - npm ci
    - npm run test --workspace=@drupal-canvas/ui -- --reporter=junit --outputFile=$CI_PROJECT_DIR/ui-vitest-junit.xml
  artifacts:
    expose_as: junit
    expire_in: 6 mos
    when: always
    name: artifacts-$CI_PIPELINE_ID-$CI_JOB_NAME_SLUG
    paths:
      - ui-vitest-junit.xml
    reports:
      junit: ui-vitest-junit.xml

.cypress-base:
  stage: test
  needs:
    - composer
    - UI
  rules:
    - *e2e-tests-are-enabled-rule
    - *manual-rule
  extends:
    - .test-variables
  before_script:
    - echo -e "\e[0Ksection_start:`date +%s`:Cypress-deps[collapsed=true]\r\e[0KInstall Cypress dependencies."
    # Remove Yarn repository to avoid GPG key errors (we use npm, not yarn)
    - sudo rm -f /etc/apt/sources.list.d/yarn.list
    - sudo apt-get -y update
    - sudo apt-get -y install libgtk2.0-0t64 libgtk-3-0t64 libgbm-dev libnotify-dev libnss3 libxss1 libasound2t64 libxtst6 xauth xvfb alsa-utils pulseaudio
    - echo "pcm.!default { type pulse }" > ~/.asoundrc
    - echo "ctl.!default { type pulse }" >> ~/.asoundrc
    - pulseaudio --system --disallow-exit --disallow-module-loading &
    - echo -e "\e[0Ksection_end:`date +%s`:Cypress-deps\r\e[0K"
    #
    # Copied from `.nightwatch-base`, but converted to use GitLab CI references.
    # 👇
    #
    - !reference [ .setup-webserver ]
    - !reference [ .simpletest-db ]
    - export DRUPAL_TEST_DB_URL=$SIMPLETEST_DB
    - !reference [ .show-environment-variables ]
    - cd $_WEB_ROOT
    #
    # 👆
    #
    - cd $CI_PROJECT_DIR
    - echo -e "\e[0Ksection_start:`date +%s`:Cypress-install[collapsed=true]\r\e[0KInstall Cypress."
    - npm ci
    - cd ui
    - cp .env.example .env
    - echo "BASE_URL='${SIMPLETEST_BASE_URL}'" >> .env
    - echo "DB_URL='${DRUPAL_TEST_DB_URL}'" >> .env
    - echo "DRUPAL_TEST_WEBSERVER_USER=www-data" >> .env
    - echo "DRUPAL_ROOT_CORE='${CI_PROJECT_DIR}/${_WEB_ROOT}/core'" >> .env
    - cat .env
    - mkdir -p $CYPRESS_CACHE_FOLDER /var/www/.npm /home/apache/.cache/fontconfig ~/.cache /usr/share/fonts/ /var/cache/fontconfig
    - chown -R www-data:www-data $CYPRESS_CACHE_FOLDER /var/www/.npm /usr/bin/npm /home/apache/.cache/fontconfig ~/.cache /usr/share/fonts/ /var/cache/fontconfig
    - chmod -R 755 $CYPRESS_CACHE_FOLDER
    - sudo -u www-data CYPRESS_CACHE_FOLDER=$CYPRESS_CACHE_FOLDER npx cypress install
    - sudo -u www-data CYPRESS_CACHE_FOLDER=$CYPRESS_CACHE_FOLDER npx cypress --version
    - echo -e "\e[0Ksection_end:`date +%s`:Cypress-install\r\e[0K"
  variables:
    _TARGET_DB_TYPE: sqlite
    CYPRESS_CACHE_FOLDER: $DRUPAL_PROJECT_FOLDER/ui/cycache
  artifacts:
    when: always
    expire_in: 6 mos
    paths:
      - ui/tests/screenshots/**/*.png
    reports:
      junit:
        - ui/junit-*.xml

cypress E2E:
  extends: .cypress-base
  parallel: 4
  script:
    - npx cypress run --browser electron --reporter junit --reporter-options "mochaFile=junit-[hash].xml" --spec=`node ./tests/support/parallel.js` 2>&1 | tee cypress.log || EXIT_CODE=$?
    # Auto-retry when known frequent random failures occur.
    - grep "✖.*autocomplete-props\.cy\.js" $CI_PROJECT_DIR/ui/cypress.log && exit 112 || true
    - grep "✖.*copy-and-paste\.cy\.js" $CI_PROJECT_DIR/ui/cypress.log && exit 112 || true
    - grep "✖.*global-regions-interact\.cy\.js" $CI_PROJECT_DIR/ui/cypress.log && exit 112 || true
    - grep "✖.*media-library-component-instance\.cy\.js" $CI_PROJECT_DIR/ui/cypress.log && exit 112 || true
    # If no auto-retry was attempted, use the original exit code.
    - exit $EXIT_CODE
  retry:
    max: 2
    exit_codes: 112

cypress unit:
  extends: .cypress-base
  script:
    - npx cypress run --component --browser electron --reporter junit --reporter-options "mochaFile=junit-[hash].xml"
  rules:
    - *is-push-rule
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - ui/src/**/*
        - ui/tsconfig.json
        - ui/tsconfig.node.json
        - ui/tests/unit/**/*
    - *UI-fixtures-files-change-rule
    - *manual-rule

lint (php):
  stage: validate
  needs: []
  image: ghcr.io/drupal-canvas/drupal-testing:1.0.0
  variables:
    GIT_DEPTH: 1
    COMPOSER_ROOT_VERSION: 0.0.0
  before_script:
    - !reference [ .drupal-files ]
    - composer run install-dev-deps
    - mkdir -p test-results
  script:
    # PHPStan doesn't allow multiple outputs, but it will cache the result so
    # the second run is very fast.
    - composer run phpstan -- --error-format=junit > test-results/phpstan.xml || true
    - !reference [ .test_runner ]
    - run_test "composer validate" "composer validate --strict"
    - run_test "phpcs" "composer run phpcs"
    - run_test "phpstan" "composer run phpstan"
    - !reference [ .test_summary ]
    # Regenerate the >=11.3 ignores from scratch — this ensures we avoid manual additions.
    # (Manual additions belong in phpstan.neon; this file should be purely auto-generated ignores.)
    - composer run phpstan-regenerate-ignores-for-11.3-and-higher
    - cp phpstan-11.3-and-higher-ignores.neon test-results/
    - git diff --quiet -- phpstan-11.3-and-higher-ignores.neon && echo "✅ phpstan-11.3-and-higher-ignores.neon in sync." || (echo "❌ phpstan-11.3-and-higher-ignores.neon out of sync." && echo "🙏 Please run composer run phpstan-regenerate-ignores-for-11.3-and-higher or download the file from the CI artifacts, and commit the result." && exit 1)
  after_script:
    - cp -R _drupal/web/modules/contrib/$CI_PARENT_PROJECT_NAME/test-results $CI_PROJECT_DIR/test-results
  artifacts:
    expose_as: 'Static tests report'
    when: always
    expire_in: 6 mos
    paths:
      - test-results/
    reports:
      junit:
        - test-results/phpcs.xml
        - test-results/phpstan.xml

# This is the lint job for packages that are under the root package.json and
# workspace.
# @todo migrate the ui/ packages to the top level workspace now that we can get
# around the GitLab issues.
lint (node):
  stage: validate
  needs: []
  image: ghcr.io/drupal-canvas/drupal-testing:1.0.0
  before_script:
    - . /root/.nvm/nvm.sh && nvm install 24 && nvm alias default 24
  script:
    - npm ci
    - npm run lint

type-check:
  stage: validate
  needs: []
  image: ghcr.io/drupal-canvas/drupal-testing:1.0.0
  before_script:
    - . /root/.nvm/nvm.sh && nvm install 24 && nvm alias default 24
  script:
    - npm ci
    - npm run build --workspace=drupal-canvas
    - npm run type-check --workspaces

lint (OpenAPI):
  stage: validate
  needs: []
  image: node:24-alpine
  script:
    - npx @redocly/cli@latest lint openapi.yml
  variables:
    FORCE_COLOR: "1"

playwright:
  stage: test
  needs: []
  rules:
    - *e2e-tests-are-enabled-rule
    - *manual-rule
  interruptible: true
  image: ghcr.io/drupal-canvas/drupal-testing:1.0.0
  extends:
    - .test-variables
  variables:
    GIT_DEPTH: 1
    _TARGET_DB_TYPE: sqlite
    DRUPAL_TEST_BASE_URL: http://localhost
    DRUPAL_TEST_WEBSERVER_USER: www-data
    DRUPAL_TEST_PLAYWRIGHT_SKIP_TEARDOWN: true
    COMPOSER_IGNORE_PLATFORM_REQS:
  before_script:
    - !reference [ .drupal ]
    - composer run install-dev-deps
  script:
    - npm ci
    - npm run test:playwright | tee $CI_PROJECT_DIR/playwright.log || EXIT_CODE=$?
    # Auto-retry when a single failure occurs (because only "3 failed" suggests a systemic failure: a failure on all 3
    # browsers. Any human would manually click "retry", so automate it).
    - grep "1 failed" $CI_PROJECT_DIR/playwright.log && exit 112 || true
    # If no auto-retry was attempted, use the original exit code.
    - exit $EXIT_CODE
  after_script:
    - cp -R _drupal/web/modules/contrib/$CI_PARENT_PROJECT_NAME/test-results $CI_PROJECT_DIR/test-results
    - cp -R _drupal/web/modules/contrib/$CI_PARENT_PROJECT_NAME/playwright-report $CI_PROJECT_DIR/playwright-report
    - |
      cat > $CI_PROJECT_DIR/test-results/links.json << EOF
      {
        "playwright": [
          {
            "external_link": {
              "label": "Playwright test report",
              "url": "https://${CI_PROJECT_NAMESPACE}.${CI_PAGES_DOMAIN}/-/${CI_PROJECT_NAME}/-/jobs/${CI_JOB_ID}/artifacts/playwright-report/index.html"
            }
          }
        ]
      }
      EOF
  artifacts:
    expose_as: 'Playwright Test Reports'
    when: always
    expire_in: 6 mos
    paths:
      - playwright-report/
      - test-results/
    reports:
      junit:
        - test-results/playwright.xml
      annotations: test-results/links.json
  retry:
    max: 2
    exit_codes: 112

CLI Test:
  stage: test
  image: ghcr.io/drupal-canvas/drupal-testing:1.0.1
  needs: []
  rules:
    - changes:
        - "packages/cli/**/*"
        - package.json
        - package-lock.json
        - openapi.yml
        - src/Entity/JavaScriptComponent.php
        - src/Controller/ApiConfigControllers.php
        # CLI Test checks these components so changes may affect test results.
        - tests/modules/canvas_test_code_components/**/*
    - if: '$CI_COMMIT_TAG =~ /^cli-\d+\.\d+\.\d+(-\w+\d*)?$/'
    - *manual-rule
  variables:
    GIT_DEPTH: 1
    _TARGET_DB_TYPE: sqlite
    TEST_CANVAS_CLIENT_ID: cli
    TEST_CANVAS_CLIENT_SECRET: secret
    DRUPAL_TEST_WEBSERVER_USER: www-data
    DRUPAL_TEST_BASE_URL: http://localhost
  before_script:
    - !reference [ .drupal ]
    - composer run install-dev-deps
    - mkdir -p test-results
  # This job must pass, but must also not disrupt Canvas's CI if dependencies have a security vulnerability.
  allow_failure:
    exit_codes:
      # `npm audit …` fails (implies upstream security vulnerability that may or may not affect Canvas)
      - 100
  script:
    - npm ci
    - npm run test --workspace=@drupal-canvas/cli
    - npm run build --workspace=@drupal-canvas/cli
    - npm version 0.0.1 --workspace=@drupal-canvas/cli
    - npm pack --pack-destination=test-results --workspace=@drupal-canvas/cli
    - npm audit --audit-level=moderate --production || exit 100
  artifacts:
    expose_as: 'CLI package'
    when: always
    expire_in: 6 mos
    paths:
      - test-results/

CLI Publish:
  stage: publish
  image: node:20-alpine
  needs:
    - lint (node)
    - CLI Test
  rules:
    - if: '$CI_COMMIT_TAG =~ /^cli-\d+\.\d+\.\d+(-\w+\d*)?$/'
  before_script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
  script:
    - npm ci
    - npm run build --workspace=@drupal-canvas/cli
    - npm version $(echo ${CI_COMMIT_TAG} | cut -c5-) --workspace=@drupal-canvas/cli
    - npm publish --access public --workspace=@drupal-canvas/cli

# User facing documentation.
pages-mr:
  image: node:22
  stage: publish
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - "docs/user/**/*"
  variables:
    ASTRO_SITE: https://$CI_PAGES_HOSTNAME
    ASTRO_BASE: /$CI_PROJECT_NAME/mr-$CI_MERGE_REQUEST_IID/
  script:
    - npm ci
    - npm run build --workspace=docs
  pages:
    publish: docs/user/dist
    path_prefix: "mr-$CI_MERGE_REQUEST_IID"
    expire_in: 1 month
  environment:
    name: pages/mr-$CI_MERGE_REQUEST_IID
    url: $CI_PAGES_URL
    on_stop: stop-pages-mr

stop-pages-mr:
  stage: publish
  needs: []
  rules:
    # Branch merge.
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_MERGE_REQUEST_IID
      changes:
        - "docs/user/**/*"
    # Branch deletion.
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BEFORE_SHA != "0000000000000000000000000000000000000000" && $CI_COMMIT_SHA == "0000000000000000000000000000000000000000"
      changes:
        - "docs/user/**/*"
  script:
    - echo "Stopping pages deployment for MR $CI_MERGE_REQUEST_IID"
  environment:
    name: pages/mr-$CI_MERGE_REQUEST_IID
    action: stop

pages-publish:
  image: node:22
  stage: publish
  needs: []
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - "docs/user/**/*"
  variables:
    ASTRO_SITE: https://$CI_PAGES_HOSTNAME
    ASTRO_BASE: /$CI_PROJECT_NAME/
  script:
    - npm ci
    - npm run build --workspace=docs
  pages:
    publish: docs/user/dist

release:
  # For release flow details, see docs/release-process.md.
  stage: publish
  image: ghcr.io/drupal-canvas/drupal-testing:1.0.2
  needs: []
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
  before_script:
    - export VERSION=$(echo ${CI_COMMIT_TAG} | cut -c2-)
    - git config --global user.email "no-reply@drupal.org"
    - git config --global user.name "drupal.org GitLab CI"
    - git remote set-url origin https://gitlab-ci-token:${GITLAB_CI_RELEASE_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
  script:
    - |
      npm ci
      cd ui
      npm version $VERSION --allow-same-version --no-git-tag-version
      npm run build
      cd ..
    - echo "!/ui/dist" >> .gitignore
    - echo "!/packages/astro-hydration/dist" >> .gitignore
    - git add .gitignore
    - git add ui/dist
    - git add packages/astro-hydration/dist
    - git commit -m "Add built assets for release ${VERSION}"
    - git tag -f $VERSION
    - git push origin $VERSION
    - git archive --format=zip --prefix="${CI_PROJECT_NAME}-${VERSION}/" HEAD > ${CI_PROJECT_NAME}-${VERSION}.zip
  artifacts:
    expose_as: 'Release archive'
    paths:
      - '${CI_PROJECT_NAME}-${VERSION}.zip'
    expire_in: never
